### ISSUE TITLE
Issue Compiling in Visual Studio 2022

### ISSUE THREAD

**Issue by nerdburt** [DonTuel/Hercules_DASD_Utility#1]
Hello, sorry this is likely a newbie question.   Wondering if anyone has a compiled version of this utility for Windows 10, either 32 bit or 64 bit.   Am trying to compile the executable from the project, in Visual Studio 2022, and I keep getting errors such as CS1061: 	'string' does not contain a definition for 'IsNumeric' and no accessible extension method 'IsNumeric' accepting a first argument of type 'string' could be found (are you missing a using directive or an assembly reference?)	  I presume something is missing in the path, or I am compiling the CustomExtensions.DLL wrong    

Also wondering if perhaps I am using the wrong version of .NET.  Tried a few versions and it still will not compile.  Suspect solution is very simple.

**Comment by DonTuel** [comment]
Did you download the CustomExtensions project? I marked it as an external reference, but GitHub doesn't automatically pull it along with the main project. I'll update the dependencies to reflect that.

I last compiled with Visual Studio 2019 using .NET Framework 4.6.1.

Hope that helps.

**Comment by nerdburt** [comment]
Hello, yes that helps.   I was wondering if you used Windows 7 or Windows 10?    I cannot seem to find the .NET Framework 4.6.1 SDK, though the runtime is still available.   I do have the CustomExtensions project, but it seems to ignore it.   Maybe I need to copy the DLL somewhere?

**Comment by nerdburt** [comment]
Good evening, I managed to get Visual Studio 2019 working and installed .NET Framework 4.6.1 SDK.  I installed the utility along with the CustomExtensions projects and it compiled immediately.  Thanks for the clarification.  I am unsure as to why it does not compile with 2022.    

So far, when running the executable with Windows 10, I do not get a GUI nor command prompt.  I am using Windows 10/21H2.  
I checked the application logs and this is the error.  Will try a few more things.

Application: Hercules DASD Utility.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Hercules_DASD_Utility.XMLConfiguration.Load(System.String)
   at Hercules_DASD_Utility.DASD_Utilities.LoadConfiguration()
   at Hercules_DASD_Utility.DASD_Utilities.MyInitialize()
   at Hercules_DASD_Utility.DASD_Utilities..ctor()
   at Hercules_DASD_Utility.Program.Main()

Faulting application name: Hercules DASD Utility.exe, version: 1.0.0.0, time stamp: 0x62859fa7
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x08af64b5
Faulting process id: 0x2154
Faulting application start time: 0x01d86b2138d1ec35
Faulting application path: C:\Users\...\Source\Repos\Hercules_DASD_Utility\Hercules_DASD_Utility\bin\Debug\Hercules DASD Utility.exe
Faulting module path: unknown
Report Id: 4c3a49b2-21e1-412c-9890-d8ab5a963b88
Faulting package full name: 
Faulting package-relative application ID:

**Comment by DonTuel** [comment]
I use Windows 10 Pro 21H1, OS build 19043.1706, Experience Pack 120.2212.4170.0

Sorry to hear about your issues. I'll download it onto my laptop as I've never installed it there and try compiling it. I will not be able to work on it until this weekend. I'll let you know what I find. I'll probably download Visual Studio 2022 at the same time and see what's up with that.

Thanks for the heads up on Visual Studio,
Don Tuel

**Comment by nerdburt** [comment]
Hello, thanks for the kind review of the issue.  No major rush, just curious to try this out, as I would like to crack open some DASD’s for another project I am working on for the mainframe.

I think Visual Studio 2019 almost gets it running.  It crashes in the debugger with attached.  I apologize in advance for not really knowing what I am doing, but am learning 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by DonTuel** [comment]
I think I found the issue. The XMLConfiguration routine was not creating or saving the XML file properly if it did not exist. I, unfortunately, borrowed that code from an old program of mine after I had already created the file. I also fixed a couple of other issues I found recently.

I will take a look at Visual Studio 2022, soon. After I look at VS 2022 I'll look at updating the documentation to help the next person trying this out.

Let me know if you have any further problems.

**Comment by nerdburt** [comment]
Good morning, thank you, these updates have corrected the issue.   There are zero compilation errors, and I was able to launch the release executable.   I also tried a fresh compile from VS 2022, and it worked on the first try, so the issues corrected apply to both VS 2019 and 2022.   Excellent work, thank you so much!
